In [1]:
import pandas as pd

In [ ]:
nyc_neighborhoods = pd.read_html('https://en.wikipedia.org/wiki/Neighborhoods_in_New_York_City')[0]
print(nyc_neighborhoods.shape)
nyc_neighborhoods

In [3]:
from geopy.geocoders import Nominatim
import requests

---

In [41]:
nyc_median_income = pd.read_csv('data/nyc-sub-borougharea-medianhouseholdincome2018.csv').iloc[:,[2,-1]]

In [35]:
nyc_median_income.head()

                       Sub-Borough Area           2017
0            Stuyvesant Town/Turtle Bay  114526.279245
1                       Upper West Side  126256.807888
2                       Upper East Side  133852.964651
3  Morningside Heights/Hamilton Heights   51002.475674
4                        Central Harlem   49994.614252

In [56]:
address = 'Stuyvesant Town, New York City, NY'

geolocator = Nominatim(user_agent="ny_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of New York City are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of New York City are 40.7319711, -73.978092781304.

In [72]:
np.mean([])

nan

In [74]:
import numpy as np


geolocator = Nominatim(user_agent="ny_explorer")

for i in nyc_median_income.index:
    lat, lng = [], []
    names = nyc_median_income.loc[i,'Sub-Borough Area'].split('/')
    for name in names:
        location = geolocator.geocode(name + ', New York City, NY')
        if location is not None:
            lat.append(location.latitude)
            lng.append(location.longitude)
    print('{}:\t{}, {}.'.format(i, lat, lng))
    if len(lat) > 0:
        nyc_median_income.loc[i,'Latitude'] = np.mean(lat)
        nyc_median_income.loc[i,'Longitude'] = np.mean(lng)

0:	[40.7319711, 40.7534666], [-73.978092781304, -73.9688659].
1:	[40.7870455], [-73.9754163].
2:	[40.7737016], [-73.9641196].
3:	[40.81, 40.8241451], [-73.9625, -73.9500618].
4:	[40.8078786], [-73.9454154].
5:	[40.7947222], [-73.9425].
6:	[40.8401984, 40.8692579], [-73.9402214, -73.9204949].
7:	[40.8089897, 40.8126008], [-73.9229147, -73.8840247].
8:	[40.8292672, 40.8552778], [-73.9065253, -73.8863889].
9:	[40.8460552], [-73.9297329337184].
10:	[40.8601, 40.8592667], [-73.909303, -73.8984694].
11:	[40.8725702, 40.8797256], [-73.9026619, -73.8846982].
12:	[40.90056, 40.8787051], [-73.90639, -73.9051408].
13:	[40.8294972, 40.8389893], [-73.8746243, -73.8604128].
14:	[40.8226008, 40.8738889], [-73.8195784, -73.8294444].
15:	[40.8592334], [-73.8550166].
16:	[40.8772494, 40.8612222], [-73.8655145, -73.8412865].
17:	[40.714622, 40.7237134], [-73.95345, -73.9509714].
18:	[40.7319802, 40.7076124], [-73.9965658, -74.009378].
19:	[40.7159357, 40.7164913], [-73.9868057, -73.9962504].
20:	[40.7464906, 40.7644228, 40.7622684], [-74.0015283, -73.9923918, -73.9795443].
21:	[40.6537148], [-73.9304151].
22:	[40.6212155, 40.643715], [-73.9348597, -73.9006921].
23:	[40.69608485, 40.6907711], [-73.9950278391265, -73.9766245].
24:	[40.6834364], [-73.9412488].
25:	[40.6942696], [-73.9187482].
26:	[40.6667702, 40.6478541], [-73.8823583, -73.8795154568842].
27:	[40.6701033, 40.6784201], [-73.9859723, -73.9948021].
28:	[40.644337], [-74.007532].
29:	[40.667471, 40.6778708], [-73.9435662, -73.9684725].
30:	[40.667471], [-73.9435662].
31:	[40.630188], [-74.0271902].
32:	[40.6049772], [-73.9934061].
33:	[40.633993], [-73.9968059].
34:	[40.575789], [-73.985145].
35:	[40.6520481], [-73.959027].
36:	[40.5912161, 40.5961338], [-73.9445822, -73.9739426].
37:	[40.6672357, 40.6757317], [-73.9067979, -73.9124338].
38:	[40.7720145], [-73.9302673].
39:	[40.7398242, 40.7461604], [-73.9354153, -73.9032853].
40:	[40.7556561], [-73.8857755].
41:	[40.7365804, 40.7469593], [-73.8783932, -73.8601456].
42:	[40.7182153, 40.7080556], [-73.8786698186696, -73.9141667].
43:	[40.72293705, 40.7195766], [-73.8622065151304, -73.8448686].
44:	[40.744181, 40.7945457], [-73.8358541, -73.8184674].
45:	[42.3792319, 40.73613835], [-78.2052895, -73.7800816557486].
46:	[40.67677, 40.6892698], [-73.8437461, -73.8579131].
47:	[40.6701035, 40.6578815], [-73.8190231, -73.8362459].
48:	[40.7684351, 40.7620463], [-73.7770774, -73.7381874].
49:	[40.6914852], [-73.8056771].
50:	[40.7267692], [-73.7415208].
51:	[40.58937475], [-73.8015675874329].
52:	[44.0347778], [-76.2788215].
53:	[40.6220596], [-73.5185421].
54:	[], [].

In [75]:
nyc_median_income

                        Sub-Borough Area           2017   Latitude  Longitude
0             Stuyvesant Town/Turtle Bay  114526.279245  40.742719 -73.973479
1                        Upper West Side  126256.807888  40.787045 -73.975416
2                        Upper East Side  133852.964651  40.773702 -73.964120
3   Morningside Heights/Hamilton Heights   51002.475674  40.817073 -73.956281
4                         Central Harlem   49994.614252  40.807879 -73.945415
5                            East Harlem   37471.248212  40.794722 -73.942500
6              Washington Heights/Inwood   57457.272687  40.854728 -73.930358
7                 Mott Haven/Hunts Point   21365.846887  40.810795 -73.903470
8                     Morrisania/Belmont   26467.317339  40.842272 -73.896457
9             Highbridge/South Concourse   31489.300238  40.846055 -73.929733
10            University Heights/Fordham   30741.301974  40.859683 -73.903886
11           Kingsbridge Heights/Mosholu   36029.262457  40.876148 -73.893680
12                 Riverdale/Kingsbridge   55015.578080  40.889633 -73.905765
13                 Soundview/Parkchester   40767.943561  40.834243 -73.867519
14                Throgs Neck/Co-op City   60657.156271  40.848245 -73.824511
15                        Pelham Parkway   48933.761128  40.859233 -73.855017
16             Williamsbridge/Baychester   59893.871939  40.869236 -73.853400
17               Williamsburg/Greenpoint   78069.006882  40.719168 -73.952211
18  Greenwich Village/Financial District  147640.998056  40.719796 -74.002972
19             Lower East Side/Chinatown   40338.914584  40.716214 -73.991528
20               Chelsea/Clinton/Midtown  103925.900570  40.757727 -73.991155
21                         East Flatbush   50290.144902  40.653715 -73.930415
22                    Flatlands/Canarsie   78108.750659  40.632465 -73.917776
23          Brooklyn Heights/Fort Greene   94327.268889  40.693428 -73.985826
24                    Bedford Stuyvesant   52896.929044  40.683436 -73.941249
25                              Bushwick   51622.070967  40.694270 -73.918748
26           East New York/Starrett City   37487.553352  40.657312 -73.880937
27            Park Slope/Carroll Gardens  137374.874736  40.674262 -73.990387
28                           Sunset Park   57869.996525  40.644337 -74.007532
29  North Crown Heights/Prospect Heights   61253.312926  40.672671 -73.956019
30                   South Crown Heights   52046.004588  40.667471 -73.943566
31                             Bay Ridge   69988.791297  40.630188 -74.027190
32                           Bensonhurst   54513.175976  40.604977 -73.993406
33                          Borough Park   46229.146149  40.633993 -73.996806
34                          Coney Island   36806.813787  40.575789 -73.985145
35                              Flatbush   57678.411139  40.652048 -73.959027
36              Sheepshead Bay/Gravesend   62442.569023  40.593675 -73.959262
37                Brownsville/Ocean Hill   20640.268189  40.671484 -73.909616
38                               Astoria   67647.984739  40.772014 -73.930267
39                    Sunnyside/Woodside   68643.617306  40.742992 -73.919350
40                       Jackson Heights   57680.449281  40.755656 -73.885775
41                       Elmhurst/Corona   52983.550097  40.741770 -73.869269
42              Middle Village/Ridgewood   72592.518226  40.713135 -73.896418
43                Rego Park/Forest Hills   76885.865213  40.721257 -73.853538
44                   Flushing/Whitestone   52262.047684  40.769363 -73.827161
45               Hillcrest/Fresh Meadows   65225.652484  41.557685 -75.992686
46                  Ozone Park/Woodhaven   71249.382377  40.683020 -73.850830
47         South Ozone Park/Howard Beach   75300.190418  40.663993 -73.827634
48                   Bayside/Little Neck   71492.940396  40.765241 -73.757632
49                               Jamaica   62846.121220  40.691485 -73.805677
50                        Queens Village   87494.396458  40.726769 -73.741521
51                             Rockaways   55042.073931  40.589375 -73.801568
52                           North Shore   64069.006666  44.034778 -76.278822
53                            Mid-Island   83041.055292  40.622060 -73.518542
54                           South Shore   98642.016371        NaN        NaN

https://catalog.data.gov/dataset/neighborhood-names-gis

In [85]:
!wget -q -O "data//Neighborhood Names GIS.json" https://data.cityofnewyork.us/api/views/xyye-rtrs/rows.json?accessType=DOWNLOAD
print('Neighborhood Names GIS.json was imported successfully!')

Neighborhood Names GIS.json was imported successfully!

Boundaries of Neighborhood Tabulation Areas  
https://catalog.data.gov/dataset/neighborhood-tabulation-areas/resource/ea539dc4-f912-44f5-85d7-da2ec41465bd

In [85]:
!wget -q -O "data//Neighborhood Names GIS.json" https://data.cityofnewyork.us/api/views/q2z5-ai38/rows.json?accessType=DOWNLOAD
print('Neighborhood Names GIS.json was imported successfully!')

Neighborhood Names GIS.json was imported successfully!

2010 Census Tracts (water areas included)  
https://catalog.data.gov/dataset/2010-census-tracts-water-areas-included

In [87]:
!wget -q -O "data//Census Tracts.json" https://data.cityofnewyork.us/api/views/ghm7-s8ah/rows.json?accessType=DOWNLOAD
print('Census Tracts.json was imported successfully!')

Census Tracts.json was imported successfully!

In [86]:
# download countries geojson file
!wget --quiet https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DV0101EN/labs/Data_Files/world_countries.json -O world_countries.json
    
print('GeoJSON file downloaded!')

GeoJSON file downloaded!